spring:
  profiles.active: local
server:
  port: 9011
security:
  basic:
    enabled: false

management:
  context-path: /manage
  security:
    enabled: false

#endpoints.env.id=env
#endpoints.env.sensitive=true
#endpoints.env.enabled=true
endpoints:
  env:
    keys-to-sanitize: pwd,uid,password,secret,key,client_id,client_key # suffix or regex


#management.context-path=/manage
#management.security.enabled=false
#endpoints.env.id=env
#endpoints.env.sensitive=true
#endpoints.env.enabled=true
#endpoints.env.keys-to-sanitize=pwd,uid,password,secret,key # suffix or regex
#endpoints.health.id=health
#endpoints.health.sensitive=true
#endpoints.health.enabled=true
#endpoints.health.mapping.*= # mapping of health statuses to HttpStatus codes
#endpoints.health.time-to-live=1000
#endpoints.info.id=info
#endpoints.info.sensitive=false
#endpoints.info.enabled=true

logging:
  level:
    io.pivotal.sfdc: INFO
#eureka.client.registerWithEureka = true
#eureka.client.fetchRegistry = true
#eureka.client.registryFetchIntervalSeconds = 10
#eureka.instance.leaseRenewalIntervalInSeconds = 30
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka/
  instance:
    statusPageUrlPath: ${management.context-path}/health
    healthCheckUrlPath: ${management.context-path}/health
    hostname: ${vcap.application.uris[0]:localhost}
    registryFetchIntervalSeconds: 5
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#eureka.client.registerWithEureka = true
#eureka.client.fetchRegistry = true
#eureka.client.registryFetchIntervalSeconds = 10
#eureka.instance.leaseRenewalIntervalInSeconds = 30

zuul:
  routes:
    authservice: /authservice/**
    accountservice: /accountservice/**
    contactservice: /contactservice/**
    opportunityservice: /opportunityservice/**

sfdc:
  service:
    unavailable: '{"status":503,"data":"Service currently unavailable."}'

---
spring:
  profiles: local
eureka:
  instance:
    nonSecurePort: ${server.port}
---
spring:
  profiles: cloud # For deployment in Cloud Foundry
eureka:
  instance:
    securePortEnabled: true
    nonSecurePortEnabled: false
    #nonSecurePort: 80
    secureVirtualHostName: ${spring.application.name}
ribbon:
  IsSecure: true
