= Running the labs locally

You will need to link:++https://docs.docker.com/engine/installation/++[install Docker]

Once Docker is installed, start up the Docker CLI

. Retrieve Docker Machine IP
+
----
$ docker-machine ip
192.168.99.100

# Go to Project's root directory and locate docker-compose.yml file.
$ cd $PROJECT_HOME
# Run the end-to-end integration in background
$ docker-compose up -d
# Monitor the logs
$ docker-compose logs
# Shutdown all the container
$ docker-compose down

# To test the circuit-breaker, you can shutdown one of the service
$ docker ps

$ docker stop <CONTAINER ID>

----

== Test Application

Config Git Repo URL: https://github.com/jigsheth57/config-repo
You can override the repo value for Config Server in docker-compose.yml file
Test Config Server to make sure it's pointing to correct config-repo
$ open http://`docker-machine ip default`:8888/authService/default

Service Discovery URL: http://$DOCKER-MACHINE-IP:8761/
$ open http://`docker-machine ip default`:8761/

Note: you may need to initiate oAuth session before trying out WebUI. Call http://$DOCKER-MACHINE-IP:9000/oauth2
or run bash script: ./testpcf.sh http://`docker-machine ip default`:9011

Web UI URL: http://$DOCKER-MACHINE-IP:9090/
$ open http://`docker-machine ip default`:9090/

Hystrix Dashboard URL: http://$DOCKER-MACHINE-IP:7979/
$ open http://`docker-machine ip default`:7979/hystrix/monitor?stream=http%3A%2F%2F`docker-machine ip default`%3A8000%2Fturbine.stream&title=SFDC%20App

Turbine Stream URL: http://$DOCKER-MACHINE-IP:8000/turbine.stream

You can perform stress test to lightup the Hystrix Dashboard ..
$ ab -n 1000 -c 3 http://`docker-machine ip default`:9011/contactservice/contact/003i000000eXDVVAA4
