spring:
  profiles.active: local
  redis:
    host: ${vcap.services.p-redis.credentials.host:redis}
    port: ${vcap.services.p-redis.credentials.port:6379}
    password: ${vcap.services.p-redis.credentials.password:guest}
server:
  port: 9001
security:
  basic:
    enabled: false

management:
  context-path: /manage
  security:
    enabled: false

endpoints:
  env:
    keys-to-sanitize: pwd,uid,password,secret,key,client_id,client_key # suffix or regex

logging:
  level:
    com.netflix: INFO
    org.springframework.cloud: DEBUG
    io.pivotal.sfdc: DEBUG

info:
  component: Account Service
  app:
    name: ${project.name:accountService}
    version: ${project.version:0.0.1-SNAPSHOT}
    group: ${project.groupId:io.pivotal.sfdc}
    artifact: ${project.artifactId:accountService}

eureka:
  instance:
    #preferIpAddress: false
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    registryFetchIntervalSeconds: 5
    leaseRenewalIntervalInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true

sfdc:
  service:
    unavailable: '{"status":503,"data": "Service currently unavailable."}'
  authservice:
    endpoint: http://authservice
  query:
    accounts: select account.id, account.name, account.type, (select contact.id, contact.lastname from account.contacts) from account
    opp_by_accts: select account.id, account.name, account.type, (select opportunity.id, opportunity.name, opportunity.type, opportunity.amount, opportunity.stagename, opportunity.closedate from account.opportunities) from account

test:
  message: Hello, Steve!

---
spring:
  profiles: local
  instance:
    nonSecurePort: ${server.port}
  redis:
    create-jedis-connection-factory: true
eureka:
  instance:
    hostname: accountservice
    nonSecurePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: route
  redis:
    create-jedis-connection-factory: false
eureka:
  instance:
    securePortEnabled: true
    nonSecurePortEnabled: false
    secureVirtualHostName: ${spring.application.name}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
